# Generated by Django 5.2.5 on 2025-08-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
