# Generated by Django 5.2.5 on 2025-08-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_moto_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Moto',
                'verbose_name_plural': 'Modelos de Motos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('marca', 'modelo', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='MotoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cantidad_stock', models.IntegerField(default=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='motos.motomodelo')),
            ],
            options={
                'verbose_name': 'Inventario de Moto',
                'verbose_name_plural': 'Inventario de Motos',
                'ordering': ['-fecha_ingreso'],
                'unique_together': {('modelo', 'color', 'chasis')},
            },
        ),
    ]
