# Generated by Django 5.2.5 on 2025-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_motomodelo_motoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoinventario',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje para este color específico', max_digits=5),
        ),
    ]
