# Generated by Django 5.2.5 on 2025-08-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0004_motoinventario_descuento_porcentaje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motoinventario',
            unique_together=set(),
        ),
    ]
