# Generated by Django 5.2.5 on 2025-08-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0005_alter_motoinventario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='condicion',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada')], default='nueva', max_length=10, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='condicion',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada')], default='nueva', max_length=10, verbose_name='Condición'),
        ),
    ]
