# Generated by Django 5.2.5 on 2025-08-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0006_moto_condicion_motomodelo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='capacidad_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad del tanque en litros', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='cilindraje',
            field=models.IntegerField(blank=True, help_text='Cilindraje en CC', null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='combustible',
            field=models.CharField(blank=True, default='Gasolina', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='potencia',
            field=models.CharField(blank=True, help_text='Ej: 15 HP @ 8000 RPM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='tipo_motor',
            field=models.CharField(blank=True, choices=[('2_tiempos', '2 Tiempos'), ('4_tiempos', '4 Tiempos'), ('electrico', 'Eléctrico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='torque',
            field=models.CharField(blank=True, help_text='Ej: 12 Nm @ 6000 RPM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='transmision',
            field=models.CharField(blank=True, help_text='Ej: Manual 5 velocidades', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='capacidad_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad del tanque en litros', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='cilindraje',
            field=models.IntegerField(blank=True, help_text='Cilindraje en CC', null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='combustible',
            field=models.CharField(blank=True, default='Gasolina', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='potencia',
            field=models.CharField(blank=True, help_text='Ej: 15 HP @ 8000 RPM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='tipo_motor',
            field=models.CharField(blank=True, choices=[('2_tiempos', '2 Tiempos'), ('4_tiempos', '4 Tiempos'), ('electrico', 'Eléctrico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='torque',
            field=models.CharField(blank=True, help_text='Ej: 12 Nm @ 6000 RPM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='transmision',
            field=models.CharField(blank=True, help_text='Ej: Manual 5 velocidades', max_length=50, null=True),
        ),
    ]
