# Generated by Django 5.2.5 on 2025-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0007_moto_capacidad_tanque_moto_cilindraje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motomodelo',
            name='moneda_compra',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3, verbose_name='Moneda de Compra'),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='moneda_venta',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='RD', max_length=3, verbose_name='Moneda de Venta'),
        ),
    ]
