# Generated by Django 5.2.5 on 2025-08-19 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0008_motomodelo_moneda_compra_motomodelo_moneda_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('tipo_proveedor', models.CharField(choices=[('distribuidor', 'Distribuidor Oficial'), ('importador', 'Importador'), ('mayorista', 'Mayorista'), ('fabricante', 'Fabricante'), ('particular', 'Particular')], default='distribuidor', max_length=20)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC/NIT')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula')),
                ('registro_mercantil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro Mercantil')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número de teléfono válido')])),
                ('telefono2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número de teléfono válido')], verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='República Dominicana', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('persona_contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número de teléfono válido')], verbose_name='Teléfono del Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Contacto')),
                ('moneda_preferida', models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3)),
                ('terminos_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Términos de Pago')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Límite de Crédito')),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento General (%)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_inicio_relacion', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Relación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='moto',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor que suministra esta motocicleta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motos_legacy', to='motos.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='motomodelo',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor que suministra este modelo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motocicletas', to='motos.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado', 'tipo_proveedor'], name='motos_prove_estado_09831a_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='motos_prove_nombre_13a0b5_idx'),
        ),
    ]
