# Generated by Django 5.2.5 on 2025-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0009_proveedor_moto_proveedor_motomodelo_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoinventario',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha específica de compra de este lote', null=True),
        ),
        migrations.AddField(
            model_name='motoinventario',
            name='precio_compra_individual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra específico para este lote/color (si es diferente al precio base del modelo)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='motoinventario',
            name='tasa_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa del dólar al momento de la compra de este lote', max_digits=8, null=True),
        ),
    ]
