# Generated by Django 5.2.5 on 2025-08-26 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0010_motoinventario_fecha_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('numero_orden', models.PositiveIntegerField(default=1, help_text='Orden para mostrar en la UI')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pasillo',
                'verbose_name_plural': 'Pasillos',
                'ordering': ['numero_orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('estante', 'Estante'), ('piso', 'Piso'), ('colgante', 'Colgante'), ('exterior', 'Exterior'), ('especial', 'Especial')], default='estante', max_length=20)),
                ('nivel', models.CharField(blank=True, help_text='Nivel del estante (A, B, C, etc.)', max_length=20)),
                ('posicion', models.CharField(blank=True, help_text='Posición específica (1, 2, 3, etc.)', max_length=20)),
                ('capacidad_maxima', models.PositiveIntegerField(default=1, help_text='Número máximo de unidades')),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_generado', models.BooleanField(default=False)),
                ('fecha_ultimo_qr', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('reservado', models.BooleanField(default=False, help_text='Ubicación reservada temporalmente')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pasillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='motos.pasillo')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('pasillo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso Initial'), ('traslado', 'Traslado entre Ubicaciones'), ('venta', 'Venta'), ('ajuste', 'Ajuste de Inventario'), ('mantenimiento', 'Mantenimiento/Reparación'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.TextField(help_text='Razón del movimiento')),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_responsable', models.CharField(blank=True, max_length=100)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=True)),
                ('numero_documento', models.CharField(blank=True, help_text='Número de orden, factura, etc.', max_length=50)),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_ubicacion', to='motos.motoinventario')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='motos.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='motos.ubicacion')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='MotoInventarioLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_actual', to='motos.motoinventario')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_items', to='motos.ubicacion')),
            ],
            options={
                'verbose_name': 'Asignación de Ubicación',
                'verbose_name_plural': 'Asignaciones de Ubicación',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('nueva', 'Motocicletas Nuevas'), ('usada', 'Motocicletas Usadas'), ('reparacion', 'En Reparación'), ('exhibicion', 'Exhibición'), ('repuestos', 'Repuestos'), ('otros', 'Otros')], default='nueva', max_length=20)),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Número máximo de unidades')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='motos.almacen')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'unique_together': {('almacen', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='pasillo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasillos', to='motos.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='pasillo',
            unique_together={('zona', 'codigo')},
        ),
    ]
