# Generated by Django 5.2.5 on 2025-08-28 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0011_almacen_pasillo_ubicacion_movimientoinventario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='ruc',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rnc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RNC (Registro Nacional de Contribuyentes)'),
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('tipo_factura', models.CharField(choices=[('compra', 'Compra de Inventario'), ('servicio', 'Servicios'), ('gastos', 'Gastos Operativos'), ('otros', 'Otros')], default='compra', max_length=20)),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ITBIS/IVA')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción/Conceptos')),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas_proveedores/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_proveedor_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='motos.proveedor')),
            ],
            options={
                'verbose_name': 'Factura de Proveedor',
                'verbose_name_plural': 'Facturas de Proveedores',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de la Orden')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('recibida_parcial', 'Recibida Parcialmente'), ('recibida_completa', 'Recibida Completamente'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de la Orden')),
                ('condiciones_especiales', models.TextField(blank=True, null=True, verbose_name='Condiciones Especiales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='motos.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color Solicitado')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Item')),
                ('modelo_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='motos.motomodelo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='motos.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.CharField(max_length=50, unique=True, verbose_name='Número de Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('RD', 'Pesos Dominicanos (RD)'), ('EUR', 'Euros (EUR)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otros', 'Otros')], default='transferencia', max_length=20)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia/Cheque')),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Pago')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, help_text='Factura específica que se está pagando (opcional para pagos generales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_factura', to='motos.facturaproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='motos.proveedor')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_proveedor_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='facturaproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='motos_factu_proveed_2ea2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedor',
            index=models.Index(fields=['fecha_vencimiento', 'estado'], name='motos_factu_fecha_v_10ecbb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'estado'], name='motos_orden_proveed_804e63_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_entrega_esperada', 'estado'], name='motos_orden_fecha_e_d73e68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleordencompra',
            unique_together={('orden', 'modelo_moto', 'color')},
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['proveedor', 'fecha_pago'], name='motos_pagop_proveed_b77d88_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoproveedor',
            index=models.Index(fields=['factura'], name='motos_pagop_factura_ba5678_idx'),
        ),
    ]
