# Generated by Django 5.2.5 on 2025-08-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0012_remove_proveedor_ruc_proveedor_rnc_facturaproveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motomodelo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('view_precio_compra', 'Ver precio de compra de motocicletas'), ('change_precio_compra', 'Modificar precio de compra'), ('view_precio_venta', 'Ver precio de venta'), ('change_precio_venta', 'Modificar precio de venta'), ('view_ganancia', 'Ver ganancias de motocicletas'), ('export_motos', 'Exportar datos de motocicletas'), ('import_motos', 'Importar datos de motocicletas'), ('manage_inventory', 'Gestionar inventario completo'), ('view_stock_minimo', 'Ver configuraciones de stock mínimo')], 'verbose_name': 'Modelo de Moto', 'verbose_name_plural': 'Modelos de Motos'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_orden'], 'permissions': [('view_todas_ordenes', 'Ver todas las órdenes de compra'), ('create_orden_urgente', 'Crear órdenes con prioridad urgente'), ('change_estado_orden', 'Cambiar estado de órdenes'), ('cancel_orden', 'Cancelar órdenes de compra'), ('view_orden_pdf', 'Ver/descargar PDFs de órdenes'), ('receive_orden', 'Marcar órdenes como recibidas')], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'permissions': [('view_contabilidad', 'Ver contabilidad de proveedores'), ('manage_contabilidad', 'Gestionar contabilidad de proveedores'), ('create_orden_compra', 'Crear órdenes de compra'), ('approve_orden_compra', 'Aprobar órdenes de compra'), ('view_estadisticas_financieras', 'Ver estadísticas financieras'), ('manage_credito', 'Gestionar límites de crédito'), ('view_pagos', 'Ver historial de pagos'), ('create_factura', 'Crear facturas de proveedor')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
