# Generated by Django 5.2.5 on 2025-08-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tasa de interés mensual en porcentaje', max_digits=5),
        ),
    ]
