# Generated by Django 5.2.5 on 2025-08-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_tasa_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_total_con_intereses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total que pagará el cliente incluyendo intereses', max_digits=15),
        ),
    ]
