# Generated by Django 5.2.5 on 2025-08-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_monto_total_con_intereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total_con_intereses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total que pagará el cliente incluyendo intereses', max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pago_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
