# Generated by Django 5.2.5 on 2025-08-18 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_monto_inicial_alter_venta_monto_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('venta_erronea', 'Venta Errónea'), ('cliente_equivocado', 'Cliente Equivocado'), ('cancelado_por_cliente', 'Cancelado por el Cliente'), ('moto_no_disponible', 'Moto No Disponible'), ('problema_financiacion', 'Problema de Financiación'), ('error_sistema', 'Error del Sistema'), ('precio_incorrecto', 'Precio Incorrecto'), ('documentacion_incompleta', 'Documentación Incompleta'), ('otros', 'Otros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_cancelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
