# Generated by Django 5.0.7 on 2025-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtiempo',
            name='documento_soporte',
            field=models.FileField(blank=True, help_text='Documento de soporte (certificado médico, carta, etc.)', null=True, upload_to='solicitudes/documentos/'),
        ),
    ]
