# Generated by Django 5.2.5 on 2025-08-25 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_vencido', models.BooleanField(default=True, verbose_name='Pagos Vencidos')),
                ('pago_proximo', models.BooleanField(default=True, verbose_name='Pagos Próximos')),
                ('nueva_venta', models.BooleanField(default=True, verbose_name='Nuevas Ventas')),
                ('pago_recibido', models.BooleanField(default=True, verbose_name='Pagos Recibidos')),
                ('stock_bajo', models.BooleanField(default=True, verbose_name='Stock Bajo')),
                ('nueva_moto', models.BooleanField(default=True, verbose_name='Nuevas Motos')),
                ('cliente_nuevo', models.BooleanField(default=True, verbose_name='Nuevos Clientes')),
                ('venta_cancelada', models.BooleanField(default=True, verbose_name='Ventas Canceladas')),
                ('sistema', models.BooleanField(default=True, verbose_name='Notificaciones del Sistema')),
                ('recordatorio', models.BooleanField(default=True, verbose_name='Recordatorios')),
                ('mostrar_en_app', models.BooleanField(default=True, verbose_name='Mostrar en la aplicación')),
                ('enviar_push', models.BooleanField(default=True, verbose_name='Enviar notificaciones push')),
                ('enviar_email', models.BooleanField(default=False, verbose_name='Enviar por email')),
                ('push_subscription', models.JSONField(blank=True, help_text='Datos de suscripción para Web Push', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('pago_vencido', 'Pago Vencido'), ('pago_proximo', 'Pago Próximo a Vencer'), ('nueva_venta', 'Nueva Venta Registrada'), ('pago_recibido', 'Pago Recibido'), ('stock_bajo', 'Stock Bajo'), ('nueva_moto', 'Nueva Moto Registrada'), ('cliente_nuevo', 'Nuevo Cliente Registrado'), ('venta_cancelada', 'Venta Cancelada'), ('sistema', 'Notificación del Sistema'), ('recordatorio', 'Recordatorio')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('es_global', models.BooleanField(default=False, verbose_name='Para todos los usuarios')),
                ('roles_destinatarios', models.CharField(blank=True, help_text='Roles separados por coma: admin,vendedor,cobrador', max_length=100, null=True)),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional específica del tipo de notificación')),
                ('enviada_push', models.BooleanField(default=False, verbose_name='Enviada como Push')),
                ('fecha_envio_push', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'), models.Index(fields=['tipo', 'fecha_creacion'], name='notificacio_tipo_40f4c2_idx'), models.Index(fields=['prioridad', 'leida'], name='notificacio_priorid_67d918_idx')],
            },
        ),
    ]
