# Generated by Django 5.2.5 on 2025-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='propietario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fiador', 'Fiador')], default='cliente', max_length=10),
        ),
    ]
