# Generated by Django 5.2.5 on 2025-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_documento_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiador',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='parentesco_cliente',
            field=models.CharField(blank=True, help_text='Relación con el cliente (padre, hermano, amigo, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='referencias_personales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiador',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('licencia_conducir', 'Licencia de Conducir'), ('prueba_direccion', 'Prueba de Dirección')], max_length=20),
        ),
    ]
