# Generated by Django 5.2.5 on 2025-08-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rol_puede_configurar_sistema_rol_puede_crear_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
