# Generated by Django 5.2.5 on 2025-08-29 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_make_documento_descripcion_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoGranular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: motos.view_precio_compra)', max_length=100, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del permiso')),
                ('categoria', models.CharField(choices=[('motos', 'Motocicletas e Inventario'), ('proveedores', 'Proveedores y Compras'), ('clientes', 'Clientes y Ventas'), ('finanzas', 'Finanzas y Contabilidad'), ('reportes', 'Reportes y Analytics'), ('usuarios', 'Usuarios y Sistema'), ('configuracion', 'Configuración')], max_length=50)),
                ('es_critico', models.BooleanField(default=False, help_text='Permiso crítico que requiere aprobación especial')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso Granular',
                'verbose_name_plural': 'Permisos Granulares',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='usuarios.permisogranular')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_granulares', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
