# Generated by Django 5.2.5 on 2025-08-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
        ('ventas', '0004_alter_venta_monto_inicial_alter_venta_monto_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(help_text='Número de cuota (1, 2, 3...)')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, help_text='Monto de la cuota mensual', max_digits=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto ya pagado de esta cuota', max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('parcial', 'Pago Parcial'), ('vencida', 'Vencida')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_programadas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuota de Vencimiento',
                'verbose_name_plural': 'Cuotas de Vencimiento',
                'ordering': ['venta', 'numero_cuota'],
                'unique_together': {('venta', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='AlertaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('proximo_vencer', 'Próximo a Vencer'), ('vencida', 'Cuota Vencida'), ('multiple_vencidas', 'Múltiples Cuotas Vencidas')], max_length=20)),
                ('mensaje', models.TextField(help_text='Mensaje descriptivo de la alerta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('leida', 'Leída'), ('resuelta', 'Resuelta')], default='activa', max_length=10)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_pago', to='ventas.venta')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pagos.cuotavencimiento')),
            ],
            options={
                'verbose_name': 'Alerta de Pago',
                'verbose_name_plural': 'Alertas de Pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
