# Generated by Django 5.2.5 on 2025-08-18 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_cuotavencimiento_alertapago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descripcion_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('pago_erroneo', 'Pago Erróneo'), ('cliente_equivocado', 'Cliente Equivocado'), ('cancelado_por_cliente', 'Cancelado por el Cliente'), ('duplicado', 'Pago Duplicado'), ('metodo_pago_invalido', 'Método de Pago Inválido'), ('otros', 'Otros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_cancelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
    ]
